In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\mr.shoaib\Downloads\placement.csv")

In [3]:
df.head(3)

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25

In [4]:
x = df.iloc[:,:-1]
y = df["package"]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor

In [9]:
bg = BaggingRegressor(estimator=LinearRegression(),n_estimators=40)
bg.fit(x_train, y_train)

BaggingRegressor(estimator=LinearRegression(), n_estimators=40)

In [10]:
bg.score(x_train, y_train)*100

77.46860200099975

In [11]:
bg.score(x_test, y_test)*100

77.77150308155177

In [15]:
rf = RandomForestRegressor(n_estimators=50)
rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=50)

In [16]:
rf.score(x_train, y_train)*100

91.67143440638927

In [17]:
rf.score(x_test, y_test)*100

69.06110376263433

In [19]:
prd = {"bg":bg.predict(x_test),"rf":rf.predict(x_test)}

In [20]:
pd.DataFrame(prd)

          bg        rf
0   2.793667  2.907107
1   3.150424  3.297459
2   3.213719  3.022600
3   2.402385  2.483600
4   3.541705  3.857493
5   3.783379  3.832080
6   3.179194  3.258992
7   2.557747  2.272790
8   3.190703  3.309200
9   3.507180  3.218933
10  1.919038  2.047800
11  2.362106  2.562200
12  3.702821  3.839600
13  2.770650  2.245000
14  3.489918  3.232000
15  3.058357  2.791367
16  2.339090  2.444071
17  3.219473  2.997800
18  2.189482  2.356200
19  3.328802  3.457427
20  2.465681  2.488733
21  2.914504  3.178077
22  3.334556  3.457427
23  2.885733  3.049333
24  3.351819  3.668373
25  2.206745  2.162400
26  1.429936  1.799200
27  2.724617  2.844671
28  3.196457  3.304400
29  2.339090  2.444071
30  3.760363  3.567800
31  2.972045  2.972160
32  3.697067  3.772800
33  2.989308  3.097200
34  2.603780  3.106000
35  3.363327  3.624373
36  2.488697  2.333200
37  3.087128  2.973667
38  4.191923  3.726600
39  2.972045  2.972160
40  3.110145  2.555400
41  3.127407  2.748600
42  3.938741  4.009400
43  2.736126  2.844671
44  1.924792  1.906800
45  2.966291  2.813528
46  3.092882  2.973667
47  3.282769  3.318200
48  1.769430  1.578400
49  3.357573  3.624373