In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r"C:\Users\mr.shoaib\Downloads\dataset.csv")

In [4]:
df.head(5)

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f142,f143,f144,f145,f146,f147,f148,f149,f150,target
0,-0.924357,-0.326536,-1.875007,-1.780626,-0.630143,0.788204,2.792209,-0.772192,-0.450994,0.400000,...,0.968645,-0.702053,-0.327662,-0.392108,-1.463515,0.296120,0.261055,0.005113,-0.234587,10.681366
1,0.001795,-1.285599,-0.726774,0.385711,0.891863,0.599451,-0.140553,-0.761760,0.117707,0.333231,...,0.856399,0.214094,-1.245739,0.173181,0.385317,-0.883857,0.153725,0.058209,-1.142970,-60.163343
2,0.956702,2.319330,-0.705012,0.081829,0.330880,0.838491,2.493000,1.227669,-0.785989,-0.920674,...,-0.493001,-0.589365,0.849602,0.357015,-0.692910,0.899600,0.307300,0.812862,0.629629,131.226545
3,-0.982294,0.190424,1.082691,0.714610,-1.907808,0.224216,0.156973,0.556553,0.058984,-1.397118,...,0.491919,-1.320233,1.831459,1.179440,-0.469176,-1.713135,1.353872,-0.114540,1.237816,-131.889020
4,-0.057061,-0.592465,-2.850030,-1.935430,2.002427,-1.012644,1.059950,-1.000629,0.141596,-0.642776,...,1.479944,0.077368,-0.861284,1.523124,0.538910,-1.037246,-0.190339,-0.875618,-1.382800,-138.566956

In [5]:
df.shape

(200, 151)

In [6]:
df.isnull().sum()

f1        0
f2        0
f3        0
f4        0
f5        0
         ..
f147      0
f148      0
f149      0
f150      0
target    0
Length: 151, dtype: int64

In [7]:
# split features and target columns
x=df.drop(columns=["target"],axis=1)
y=df[["target"]]

In [8]:
x

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f141,f142,f143,f144,f145,f146,f147,f148,f149,f150
0,-0.924357,-0.326536,-1.875007,-1.780626,-0.630143,0.788204,2.792209,-0.772192,-0.450994,0.400000,...,0.097078,0.968645,-0.702053,-0.327662,-0.392108,-1.463515,0.296120,0.261055,0.005113,-0.234587
1,0.001795,-1.285599,-0.726774,0.385711,0.891863,0.599451,-0.140553,-0.761760,0.117707,0.333231,...,-0.446515,0.856399,0.214094,-1.245739,0.173181,0.385317,-0.883857,0.153725,0.058209,-1.142970
2,0.956702,2.319330,-0.705012,0.081829,0.330880,0.838491,2.493000,1.227669,-0.785989,-0.920674,...,-0.208122,-0.493001,-0.589365,0.849602,0.357015,-0.692910,0.899600,0.307300,0.812862,0.629629
3,-0.982294,0.190424,1.082691,0.714610,-1.907808,0.224216,0.156973,0.556553,0.058984,-1.397118,...,-0.898415,0.491919,-1.320233,1.831459,1.179440,-0.469176,-1.713135,1.353872,-0.114540,1.237816
4,-0.057061,-0.592465,-2.850030,-1.935430,2.002427,-1.012644,1.059950,-1.000629,0.141596,-0.642776,...,-0.007973,1.479944,0.077368,-0.861284,1.523124,0.538910,-1.037246,-0.190339,-0.875618,-1.382800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1.146487,-0.339530,-2.508957,0.252195,-0.384182,0.184859,-0.770425,0.613266,-1.112327,-0.166815,...,0.047515,-0.960417,1.565103,0.500333,-0.774601,-0.993825,0.307204,0.044206,0.832110,0.546968
196,-0.357029,-1.091701,0.534506,-2.153343,1.051948,-0.526035,0.420973,1.995667,0.890383,0.497743,...,0.457401,0.138976,0.417681,0.093365,-0.659427,0.004001,-0.714387,-0.780377,-0.336150,-0.119423
197,0.099314,0.023081,-2.367478,0.309727,-0.220018,-1.680870,0.395599,0.633225,-0.390409,-0.948749,...,0.893473,-0.519942,1.021659,0.059655,-0.163061,0.756115,-0.531876,-0.286706,0.670167,-0.031396
198,-0.051119,0.030476,-0.111319,0.520689,0.257253,0.466431,-0.702911,-0.545087,0.016125,-2.707544,...,0.727490,-2.205935,-0.733608,-0.725518,1.187127,-1.113844,0.226657,-0.128128,1.043043,0.595832
199,-0.592464,-0.562168,0.288694,-0.088363,-0.646227,-0.109610,0.006422,1.000582,-0.026406,-1.748532,...,1.232867,-0.468661,0.888839,0.902492,0.952591,0.387827,1.377367,0.378354,1.713530,-1.619920

In [9]:
y

         target
0     10.681366
1    -60.163343
2    131.226545
3   -131.889020
4   -138.566956
..          ...
195  -18.681830
196  234.589644
197  -94.329646
198   80.152034
199  110.131842

[200 rows x 1 columns]

In [10]:
# apply train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train, y_train

(           f1        f2        f3        f4        f5        f6        f7  \
 79   0.061680 -1.615132  1.492689 -2.362932 -0.100154  0.903935 -2.921350
 197  0.099314  0.023081 -2.367478  0.309727 -0.220018 -1.680870  0.395599
 38   0.197917 -2.371659  0.591442  0.839664 -2.036221 -0.532725  0.819925
 24   0.862393  1.124113  1.056057  0.351448 -1.773032  0.708304  0.754291
 122  0.504483  1.868818 -0.856852  0.025211  0.243657  0.698689  0.892068
 ..        ...       ...       ...       ...       ...       ...       ...
 106  0.731871  0.349650  0.171839  0.333860 -0.907756 -0.134497 -0.244080
 14  -0.174354  0.572057  0.811397 -0.502975 -0.721738  0.689708  1.381454
 92   1.018923  0.910216 -1.003439 -1.190917 -0.569699  0.436236  1.466783
 179 -0.561558  0.350370  0.540909 -1.936753  0.487305  0.680230  0.223153
 102  0.243891  1.674271  0.650668  1.194214  0.867805 -1.498635  0.191451

            f8        f9       f10  ...      f141      f142      f143  \
 79  -0.226479  0.428817  0.884045  ...  1.209231 -0.024286  1.638961
 197  0.633225 -0.390409 -0.948749  ...  0.893473 -0.519942  1.021659
 38   0.404213 -0.607472  1.195481  ...  0.692858  0.582571 -0.799941
 24  -0.595661  0.953125  0.645216  ... -0.013838 -0.689728 -0.493123
 122  0.110535 -1.563034 -1.859337  ... -0.461745 -1.304003  1.126434
 ..        ...       ...       ...  ...       ...       ...       ...
 106 -0.657835  0.335058 -0.948348  ... -0.510684  0.871724  1.068550
 14   1.673452  0.225308 -0.917503  ... -0.551858  2.558199 -0.564248
 92  -0.386322 -0.594211  0.308292  ... -0.672394  0.336500 -1.566959
 179 -0.125174 -0.553090 -2.498061  ...  0.942230  1.024352 -0.429676
 102  0.254128 -1.192973 -0.234508  ... -0.998570 -1.391983 -0.879717

          f144      f145      f146      f147      f148      f149      f150
 79   0.908023 -0.707440  2.209856  0.326995 -0.835125  1.652913  2.077778
 197  0.059655 -0.163061  0.756115 -0.531876 -0.286706  0.670167 -0.031396
 38  -1.908002 -0.393053  1.001632  1.393455  0.710549  0.429341  0.379640
 24   1.443632 -1.256507  0.813205 -0.278963 -0.279760  0.790372  0.340051
 122  1.601993  0.978003  1.270529 -0.344635 -0.636257 -0.778587  0.644065
 ..        ...       ...       ...       ...       ...       ...       ...
 106 -0.088571  0.684715 -1.076955  1.377974  2.148706  0.521216 -2.084332
 14   0.184551  1.542110  2.006093  2.061504  1.208366  1.024063  0.592527
 92   0.407090  1.953060 -0.994856 -0.759802 -0.710015  0.129998 -1.063036
 179  0.315373 -1.308778  0.984950 -0.783309  0.785255 -1.149305  1.031416
 102 -0.174267  0.103118 -0.271297 -2.355703  1.574586  1.086480  0.445760

 [160 rows x 150 columns],
          target
 79   -17.334274
 197  -94.329646
 38    13.336016
 24   130.354943
 122 -350.535447
 ..          ...
 106   45.881067
 14    29.333012
 92  -146.171819
 179   77.404991
 102    5.051776

 [160 rows x 1 columns])

In [11]:
# now fit the model
lm= LinearRegression()
lm.fit(x_train,y_train)

LinearRegression()

In [12]:
lm.score(x_test,y_test)*100

86.56382496943917

In [13]:
lm.coef_

array([[ 16.09991474, -22.63376235,  28.96109738,  -5.38609505,
         -6.59142675, -17.14586485,  26.38138158,  72.18567052,
        -22.61915958, -30.22835704, -11.55296337,  -4.4899415 ,
         12.19009326,  -3.58275018, -11.51687844,   9.66448518,
         20.14591539, -10.45313204,  14.6661052 ,  82.64905762,
        -12.2080552 ,  16.75579843,  -9.05049485,  39.93369362,
          4.79024103,  -7.16223267,   0.70102237,  -0.58181591,
         -1.77336497,   4.12975986,   4.62395143,  -8.36419857,
         78.42444413,   3.6307766 ,  -1.09459776,   5.11089404,
          1.85035023,   2.49751151,   3.05190887,   6.50431128,
         -3.62701413,   0.46826063,   1.46777465,   2.45875141,
         -1.43324418,   2.95444345,  -2.51507289,  -0.39269459,
         -0.62514819,  -4.46637275, -17.87892607,  23.47855275,
         -2.26073964,   3.88326112,  34.85163853,  14.3241288 ,
        -28.79051415,  -8.14129702,  16.09691136,  33.19117032,
          9.5565303 ,   5.23151557, -16.49424669,  -1.80621724,
         14.37332998, -11.59412477,  17.51875371,  11.53637794,
         -6.44652541,  -9.88827935,   8.97839157,  -9.51888418,
         10.04622596, -29.8871577 ,  -5.92242987,   1.45819983,
         -0.62153818,   2.87751412,   0.35401519,   0.31587749,
          1.41927317,   0.35222994,  -3.684496  ,   7.40321398,
          0.38100724,   4.48635766,   6.06302095,   1.80353362,
          7.54250458,   1.49098302,   6.38865687,  -1.5713567 ,
          0.5151771 ,   0.51171514,  -2.16215451,   0.58561864,
          6.65569182,   3.88520043,  -7.43158235,  -2.91848647,
          0.47978074,   2.62370224,  -0.37412035,   0.14837353,
          1.17390546,   3.67464834,   2.38395572,  -2.16544621,
          5.78650167,   4.7775463 ,   1.81818406,  -0.85874745,
         -2.63903169,  -6.6825241 ,  -2.85999844,  -4.41028438,
         -1.20270594,  -0.91467825,  -3.21771016,  -2.46120788,
         -1.15191548,   3.65264178,   3.92358807,   2.70146867,
         -1.96429675,   2.23660027,  -1.76699083,  -0.86051013,
          2.75241126,  -0.86538069,  -0.18182279,  -7.99403672,
         -0.29619632,  -2.11185252,   1.50097536,   1.7426837 ,
         -5.4708664 ,  -3.01376959,  -3.64984677,  -4.13697723,
          1.3109445 ,   0.13412157,  -2.93040205,  -3.55684315,
          1.76530163,  -3.20693131,  -5.38989471,   3.93471188,
          1.89006553,  -7.53269528]])

In [14]:
lm.intercept_

array([-3.31438514])

In [16]:
y_pred = lm.predict(x)

In [17]:
r2_score(y, y_pred)*100

98.1982827885266