In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score

In [5]:
df =  pd.read_csv(r"C:\Users\mr.shoaib\Downloads\patient_health_data.csv")

In [6]:
df

,age,bmi,blood_pressure,cholesterol,glucose,insulin,heart_rate,activity_level,diet_quality,smoking_status,alcohol_intake,health_risk_score
0,58,24.865215,122.347094,165.730375,149.289441,22.306844,75.866391,1.180237,7.675409,No,0.824123,150.547752
1,71,19.103168,136.852028,260.610781,158.584646,13.869817,69.481114,7.634622,8.933057,No,0.852910,160.320350
2,48,22.316562,137.592457,177.342582,178.760166,22.849816,69.386962,7.917398,3.501119,Yes,4.740542,187.487398
3,34,22.196893,153.164775,234.594764,136.351714,15.140336,95.348387,3.192910,2.745585,No,2.226231,148.773138
4,62,29.837173,92.768973,276.106498,158.753516,17.228576,77.680975,7.044026,8.918348,No,3.944011,170.609655
...,...,...,...,...,...,...,...,...,...,...,...,...
245,73,33.923019,154.961623,239.257347,175.833417,11.178057,99.249455,8.894246,1.837274,No,3.200992,162.542038
246,51,18.666168,83.047215,200.890687,82.041575,21.733684,78.995462,4.904205,1.264277,No,1.492175,136.146456
247,51,25.105083,166.721498,235.416528,168.392792,2.207699,75.301051,2.447634,8.406626,No,1.201912,156.758986
248,43,34.448869,115.414667,283.119072,179.062287,15.533491,64.793160,6.022381,2.887777,No,1.559495,204.649145
249,60,27.315522,119.716383,233.508238,76.766873,15.770422,98.966585,8.305770,4.411244,Yes,1.280238,106.408929

In [7]:
df.shape

(250, 12)

In [8]:
df.isnull().sum()

age                  0
bmi                  0
blood_pressure       0
cholesterol          0
glucose              0
insulin              0
heart_rate           0
activity_level       0
diet_quality         0
smoking_status       0
alcohol_intake       0
health_risk_score    0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                250 non-null    int64
 1   bmi                250 non-null    float64
 2   blood_pressure     250 non-null    float64
 3   cholesterol        250 non-null    float64
 4   glucose            250 non-null    float64
 5   insulin            250 non-null    float64
 6   heart_rate         250 non-null    float64
 7   activity_level     250 non-null    float64
 8   diet_quality       250 non-null    float64
 9   smoking_status     250 non-null    object
 10  alcohol_intake     250 non-null    float64
 11  health_risk_score  250 non-null    float64
dtypes: float64(10), int64(1), object(1)
memory usage: 23.6+ KB

In [62]:
#Convert into int to float.

df['age']=df['age'].astype(float)
df

,age,bmi,blood_pressure,cholesterol,glucose,insulin,heart_rate,activity_level,diet_quality,smoking_status,alcohol_intake,health_risk_score
0,58.0,24.865215,122.347094,165.730375,149.289441,22.306844,75.866391,1.180237,7.675409,No,0.824123,150.547752
1,71.0,19.103168,136.852028,260.610781,158.584646,13.869817,69.481114,7.634622,8.933057,No,0.852910,160.320350
2,48.0,22.316562,137.592457,177.342582,178.760166,22.849816,69.386962,7.917398,3.501119,Yes,4.740542,187.487398
3,34.0,22.196893,153.164775,234.594764,136.351714,15.140336,95.348387,3.192910,2.745585,No,2.226231,148.773138
4,62.0,29.837173,92.768973,276.106498,158.753516,17.228576,77.680975,7.044026,8.918348,No,3.944011,170.609655
...,...,...,...,...,...,...,...,...,...,...,...,...
245,73.0,33.923019,154.961623,239.257347,175.833417,11.178057,99.249455,8.894246,1.837274,No,3.200992,162.542038
246,51.0,18.666168,83.047215,200.890687,82.041575,21.733684,78.995462,4.904205,1.264277,No,1.492175,136.146456
247,51.0,25.105083,166.721498,235.416528,168.392792,2.207699,75.301051,2.447634,8.406626,No,1.201912,156.758986
248,43.0,34.448869,115.414667,283.119072,179.062287,15.533491,64.793160,6.022381,2.887777,No,1.559495,204.649145
249,60.0,27.315522,119.716383,233.508238,76.766873,15.770422,98.966585,8.305770,4.411244,Yes,1.280238,106.408929

In [64]:
#Convert into string No,yes and numercial 0,1.

df['smoking_status']=df['smoking_status'].replace({'Yes':1, 'No':0})
df

,age,bmi,blood_pressure,cholesterol,glucose,insulin,heart_rate,activity_level,diet_quality,smoking_status,alcohol_intake,health_risk_score
0,58.0,24.865215,122.347094,165.730375,149.289441,22.306844,75.866391,1.180237,7.675409,0,0.824123,150.547752
1,71.0,19.103168,136.852028,260.610781,158.584646,13.869817,69.481114,7.634622,8.933057,0,0.852910,160.320350
2,48.0,22.316562,137.592457,177.342582,178.760166,22.849816,69.386962,7.917398,3.501119,1,4.740542,187.487398
3,34.0,22.196893,153.164775,234.594764,136.351714,15.140336,95.348387,3.192910,2.745585,0,2.226231,148.773138
4,62.0,29.837173,92.768973,276.106498,158.753516,17.228576,77.680975,7.044026,8.918348,0,3.944011,170.609655
...,...,...,...,...,...,...,...,...,...,...,...,...
245,73.0,33.923019,154.961623,239.257347,175.833417,11.178057,99.249455,8.894246,1.837274,0,3.200992,162.542038
246,51.0,18.666168,83.047215,200.890687,82.041575,21.733684,78.995462,4.904205,1.264277,0,1.492175,136.146456
247,51.0,25.105083,166.721498,235.416528,168.392792,2.207699,75.301051,2.447634,8.406626,0,1.201912,156.758986
248,43.0,34.448869,115.414667,283.119072,179.062287,15.533491,64.793160,6.022381,2.887777,0,1.559495,204.649145
249,60.0,27.315522,119.716383,233.508238,76.766873,15.770422,98.966585,8.305770,4.411244,1,1.280238,106.408929

In [30]:
x = df[["blood_pressure","cholesterol","glucose","insulin","heart_rate"]]
y = df["health_risk_score"]

In [31]:
x

     blood_pressure  cholesterol     glucose    insulin  heart_rate
0        122.347094   165.730375  149.289441  22.306844   75.866391
1        136.852028   260.610781  158.584646  13.869817   69.481114
2        137.592457   177.342582  178.760166  22.849816   69.386962
3        153.164775   234.594764  136.351714  15.140336   95.348387
4         92.768973   276.106498  158.753516  17.228576   77.680975
..              ...          ...         ...        ...         ...
245      154.961623   239.257347  175.833417  11.178057   99.249455
246       83.047215   200.890687   82.041575  21.733684   78.995462
247      166.721498   235.416528  168.392792   2.207699   75.301051
248      115.414667   283.119072  179.062287  15.533491   64.793160
249      119.716383   233.508238   76.766873  15.770422   98.966585

[250 rows x 5 columns]

In [32]:
y

0      150.547752
1      160.320350
2      187.487398
3      148.773138
4      170.609655
          ...
245    162.542038
246    136.146456
247    156.758986
248    204.649145
249    106.408929
Name: health_risk_score, Length: 250, dtype: float64

In [43]:
poly = PolynomialFeatures(degree=2) # hightest power ko batata hai.
x_poly = poly.fit_transform(x)

In [44]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
lr = LinearRegression()
lr.fit(x_poly, y)

LinearRegression()

In [50]:
lr.score(x_poly,y)*100

79.26267656462274

In [51]:
lr.intercept_

-119.94550326549646

In [55]:
lr.coef_

array([ 0.00000000e+00,  7.25682875e-01,  5.43647014e-01,  5.32556986e-01,
        7.09826419e-01,  1.65122898e+00, -5.31017272e-04, -4.84482730e-04,
       -4.54340121e-04,  2.10462481e-03, -1.84552578e-03, -6.82310438e-04,
        9.26581630e-05, -2.81675452e-03,  4.37629697e-04,  6.95520693e-05,
        1.66829564e-03, -1.37974142e-04, -5.66377205e-03, -2.18290351e-03,
       -1.27280249e-02])

In [57]:
y_pred = lr.predict(x_poly)

In [59]:
r2_score(y, y_pred)*100

79.26267656462274