In [1]:
import pandas as pd

In [6]:
df =pd.read_csv("C:/Users/mr.shoaib/Downloads/SuperStore_Sales_Dataset.csv")

In [8]:
df.head(10)

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
0,4918,CA-2019-160304,01-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.940,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.940,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.980,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,03-01-2019,05-01-2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.460,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,03-01-2019,08-01-2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.080,2,-5.2640,NaN,Online,NaN,NaN
5,8605,US-2019-116365,03-01-2019,08-01-2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,WD My Passport Ultra 1TB Portable External Har...,165.600,3,-6.2100,NaN,Online,NaN,NaN
6,8606,US-2019-116365,03-01-2019,08-01-2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Phones,AT&T 17929 Lendline Telephone,180.960,5,13.5720,NaN,Cards,NaN,NaN
7,9494,CA-2019-105207,03-01-2019,08-01-2019,Standard Class,BO-11350,Bill Overfelt,Corporate,United States,Broken Arrow,...,Furniture,Tables,Hon Practical Foundations 30 x 60 Training Tab...,1592.850,7,350.4270,NaN,COD,NaN,NaN
8,9495,CA-2019-105207,03-01-2019,08-01-2019,Standard Class,BO-11350,Bill Overfelt,Corporate,United States,Broken Arrow,...,Office Supplies,Binders,Storex Dura Pro Binders,11.880,2,5.3460,NaN,COD,NaN,NaN
9,2898,US-2019-164630,04-01-2019,09-01-2019,Standard Class,EB-13975,Erica Bern,Corporate,United States,Charlotte,...,Technology,Copiers,Hewlett Packard 310 Color Digital Copier,959.968,4,119.9960,NaN,Online,NaN,NaN

In [9]:
input_data = df.iloc[:,:-1]

In [10]:
input_data

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1
0,4918,CA-2019-160304,01-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.940,1,28.2668,NaN,Online,NaN
1,4919,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.940,3,38.2668,NaN,Online,NaN
2,4920,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,TEC-PH-10000455,Technology,Phones,GE 30522EE2,231.980,2,67.2742,NaN,Cards,NaN
3,3074,CA-2019-125206,03-01-2019,05-01-2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,OFF-ST-10003692,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.460,2,28.6150,NaN,Online,NaN
4,8604,US-2019-116365,03-01-2019,08-01-2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,TEC-AC-10002217,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.080,2,-5.2640,NaN,Online,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,907,CA-2020-143259,30-12-2020,03-01-2021,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,FUR-BO-10003441,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Fully Ass...",213.136,4,12.1176,NaN,COD,NaN
5897,1297,CA-2020-115427,30-12-2020,03-01-2021,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,OFF-BI-10002103,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",295.904,2,4.5188,1.0,Online,NaN
5898,5092,CA-2020-156720,30-12-2020,03-01-2021,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,388.024,3,-0.6048,NaN,Online,NaN
5899,909,CA-2020-143259,30-12-2020,03-01-2021,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,462.776,3,19.7910,NaN,COD,NaN
5900,5093,CA-2020-151450,31-12-2020,04-01-2021,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,2975.510,3,-0.6048,NaN,COD,NaN

In [11]:
output_data = df["ind2"]

In [12]:
output_data

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
5896   NaN
5897   NaN
5898   NaN
5899   NaN
5900   NaN
Name: ind2, Length: 5901, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data,test_size=0.25)

In [18]:
x_train

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1
1991,8374,CA-2019-152940,10-11-2019,13-11-2019,First Class,RO-19780,Rose O'Brian,Consumer,United States,San Francisco,...,OFF-ST-10000352,Office Supplies,Storage,Acco Perma 2700 Stacking Storage Drawers,29.740,1,4.4610,NaN,Cards,NaN
3999,6456,CA-2020-161102,31-07-2020,03-08-2020,First Class,EC-14050,Erin Creighton,Consumer,United States,San Francisco,...,FUR-FU-10003142,Furniture,Furnishings,"Master Big Foot Doorstop, Beige",104.960,7,11.4576,NaN,Online,NaN
5327,8977,CA-2020-156622,23-11-2020,26-11-2020,First Class,JP-15460,Jennifer Patt,Corporate,United States,Dallas,...,FUR-TA-10003008,Furniture,Tables,"Lesro Round Back Collection Coffee Table, End ...",162.785,1,-31.0335,NaN,Cards,NaN
5332,4773,CA-2020-119746,23-11-2020,27-11-2020,Standard Class,CM-12385,Christopher Martinez,Consumer,United States,Chicago,...,FUR-FU-10004909,Furniture,Furnishings,Contemporary Wood/Metal Frame,86.464,1,-4.0400,NaN,Online,NaN
5356,554,CA-2020-101945,24-11-2020,28-11-2020,Standard Class,GT-14710,Greg Tran,Consumer,United States,Houston,...,OFF-FA-10004248,Office Supplies,Fasteners,Advantus T-Pin Paper Clips,99.824,3,2.5707,NaN,COD,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4095,1921,US-2020-111423,17-08-2020,19-08-2020,First Class,EH-13765,Edward Hooks,Corporate,United States,Watertown,...,FUR-CH-10003981,Furniture,Chairs,Global Commerce Series Low-Back Swivel/Tilt Ch...,482.564,2,97.6524,NaN,Cards,NaN
1767,3696,CA-2019-142097,15-10-2019,20-10-2019,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Springfield,...,OFF-EN-10002312,Office Supplies,Envelopes,#10 Self-Seal White Envelopes,66.540,6,32.6046,NaN,Online,NaN
4200,2484,CA-2020-126067,28-08-2020,03-09-2020,Standard Class,KN-16705,Kristina Nunn,Home Office,United States,Seattle,...,FUR-TA-10000617,Furniture,Tables,Hon Practical Foundations 30 x 60 Training Tab...,1176.750,5,250.3050,NaN,COD,NaN
1385,441,CA-2019-115756,05-09-2019,07-09-2019,Second Class,PK-19075,Pete Kriz,Consumer,United States,Detroit,...,FUR-FU-10000246,Furniture,Furnishings,Aluminum Document Frame,12.220,1,3.6660,NaN,Online,NaN
5008,415,CA-2020-142636,03-11-2020,07-11-2020,Standard Class,KC-16675,Kimberly Carter,Corporate,United States,Seattle,...,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,154.860,7,65.7342,NaN,Cards,NaN

In [19]:
y_train

1991   NaN
3999   NaN
5327   NaN
5332   NaN
5356   NaN
        ..
4095   NaN
1767   NaN
4200   NaN
1385   NaN
5008   NaN
Name: ind2, Length: 4425, dtype: float64

In [20]:
y_test

4422   NaN
1231   NaN
5193   NaN
1318   NaN
2477   NaN
        ..
5378   NaN
2672   NaN
1340   NaN
1139   NaN
5625   NaN
Name: ind2, Length: 1476, dtype: float64

In [25]:
x_train.shape  , y_train.shape

((4425, 22), (4425,))

In [24]:
x_test.shape  , y_test.shape

((1476, 22), (1476,))